### ISSUE TITLE
Dashboard -> Incorrect number of teachers count

### ISSUE THREAD

**Issue by antonym8** [FayazM8/Groot-Second-Phase#131]
![Screenshot (279)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/418a5de2-c284-404f-a5b8-fd5057815477)
![Screenshot (280)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/82f87210-bae2-4bad-994e-df5df38b06d6)

**Comment by m8Swetha** [comment]
Fixed
