### ISSUE TITLE
Add teacher -> Camel case letter

### ISSUE THREAD

**Issue by antonym8** [FayazM8/Groot-Second-Phase#133]
Letter 'F' should be small case

![Screenshot (282)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/585d68fc-dd64-46e5-9f09-a67943584da4)

**Comment by m8Swetha** [comment]
Fixed

**Comment by antonym8** [comment]
@m8Swetha Experience, Family details tabs showing the camel case letter

![Screenshot (332)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/f9c87635-6a52-40e3-b9cb-04d0a427a59e)

**Comment by m8Swetha** [comment]
fixed
