### ISSUE TITLE
Edit teacher -> Updated without check the declaration checkbox

### ISSUE THREAD

**Issue by antonym8** [FayazM8/Groot-Second-Phase#134]
Validation message should display if user save update the teacher without check the declaration checkbox

[screen-capture (19).webm](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/96d42fd7-1752-43fc-97b7-8a0bfb016b8f)

**Comment by m8Swetha** [comment]
Fixed
