### ISSUE TITLE
Add teacher with existing email and mobile number

### ISSUE THREAD

**Issue by antonym8** [FayazM8/Groot-Second-Phase#135]
It should not allow to create new teacher with already existing email and mobile number

![Screenshot (283)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/a15829a5-e32f-4676-81f2-63757266bf3f)

**Comment by m8Swetha** [comment]
Backend issue

**Comment by m8Swetha** [comment]
Fixed
