### ISSUE TITLE
Circular -> Edit / Delete confirmation message

### ISSUE THREAD

**Issue by antonym8** [FayazM8/Groot-Second-Phase#160]
Confirmation message shows as "Category" instead of "Circular"

![Screenshot (303)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/37d910f6-4487-4ff0-8b92-60ecb45f4f2c)
![Screenshot (304)](https://github.com/FayazM8/Barathi-Institute-of-management-Groot-/assets/142376069/66bfe134-af6c-4c70-a8f6-62e4130703d6)

**Comment by m8Swetha** [comment]
Fixed
