### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/Groot-Second-Phase#2]
Bug Description: While shuffling the pages, the system showed this content.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Groot-Second-Phase/assets/120467524/9aca7141-45a9-4de5-9766-082aa87d5cc3)
Bug Video: 

https://github.com/M8Fayaz/Groot-Second-Phase/assets/120467524/b2aae669-95eb-48e8-af96-75e5bfb5cb59

**Comment by m8Swetha** [comment]
Due to network issue, you got like this

**Comment by M8Fayaz** [comment]
Pass
